### ISSUE TITLE
Port traffic function not working

### ISSUE THREAD

**Issue by Horci** [tomaae/homeassistant-mikrotik_router#143]
I'm not able to set up the port traffic monitoring :( All the other functions I use is working fine (HW monitoring, port status, device tracker), entities avaliable but when Iturn on the port traffic in the integration setup all my entities become unavaliable. I am doing something wrong? User rigths are granted.

Board: CRS326 
FW: 6.48
Mikrotik router integration: 1.7.2
HASS OS:  2021.8.6

**Comment by tomaae** [comment]
That means integration crashed.
Have a look into your HA log. It could be something specific to CRS326.

**Comment by tomaae** [comment]
Sorry, I missed your reply.
Something is wrong with that debug. There are no data pulled from integration, instead you have librouteros debugs in. Can you put in full debug file since HA start?

I imagine its not liking comas in interface names. Like "2,4 GHz" as it may considers it to be another entry. Do you really have an interface with coma in it?
"ether1,ether2,ether3,ether4,ether5,ether6,ether7,ether8,ether9,ether10,ether11,ether12,ether13,ether14,ether15,ether16,ether17,ether18,ether19,ether20,ether21,ether22,ether23,ether24,sfp-sfpplus1,sfp-sfpplus2,1 AP 2,4 Ghz,1 AP 5ghz,1 AP-1-1,1 AP-1-2,0 AP 2,4 Ghz,0 AP 5Ghz,0 AP-1-1,0 AP-1-2"

**Comment by Horci** [comment]
Newer tought this could be the problem, but I changed the interface name (without coma), and after a HA restart everything seems fine.

An other thing (not connected to this topic) any way in the integration to set the CPU temperature reading from F to C? Or, I need te make a template sensor and calculate inside HA?

**Comment by tomaae** [comment]
Temperature should always be in C. Mikrotik does not show in F as far as documentation shows. Mine has always been in C and cant see an option to change.
