### ISSUE TITLE
[Feature] Implement service calls

### ISSUE THREAD

**Issue by tjorim** [tomaae/homeassistant-mikrotik_router#30]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
There is another custom Mikrotik component that implements service calls for scripts. It would be nice if that feature gets integrated in this component as well. Perhaps other service calls too? (e.g. check for updates so users can automate it, the component should not check itself at an interval).

**Describe alternatives you've considered**
Use the other custom component as well.

**Additional context**
Linkt to the custom component: https://github.com/pilotak/homeassistant-mikrotik

**Comment by tomaae** [comment]
You can already execute scripts from this integration without having to manually type in the script name.
Not sure what kind of functionality you are looking for.

**Comment by tjorim** [comment]
Switches aren't made for this, services make more sense then a switch. Service calls could also get validated by the platform before executing AFAIK (to check is a certain script exists).

**Comment by tomaae** [comment]
true, but I'm validating if scripts exist when you flick the switch. I would certainly prefer some kind of button entity instead of switch, but we have to work with that we have.
main reason why I did this, is so available scripts would be populated automatically. it is much easier to work with and there is no chance of making a mistake.
not sure if having both switches and service for same functionality would be a good idea.

**Comment by tomaae** [comment]
services are implemented in master now
