### ISSUE TITLE
[Question] Is it possible to use this component in Read-Only, especially without Accounting

### ISSUE THREAD

**Issue by emresumengen** [tomaae/homeassistant-mikrotik_router#51]
Hi @tomaae ,
Congrats for the hard work, looks like you’ve done a lot here.

One question from me is related to using this component with a read-only user in Mikrotik. I’m just planning to get some system stats from multiple Mikrotik routers/APs that I have, as well as device-tracker functionality (hopefully roaming between monitored Mikrotiks will work). No fancy features like interface graphing, queue graphing etc. is required for me (as I already get them through the Dude and don’t want to overload HA with additional data).

I tried to install it, but I get constant and repeated errors, especially with accounting.

Thanks in advance...

**Comment by tomaae** [comment]
I have not tested it that way, but it should work with read, api and test permissions.
of course you wont be able to control interfaces and such without write permission.
Accounting may need write permission because it works based on snapshots which are stored in device itself.
I dont think you need to worry about overloading HA with data, unless you story history for everything.
In case you are getting errors with this kind of setup, run it in debug so we can see if there is something we can do about it. I cant promise anything since permission with mikrotik can be bit weird, but we can certainly try.

**Comment by emresumengen** [comment]
@tomaae thank you. I will run with/without debug and post outputs here, at least for reference.

(I am away from home this week, but will do as soon as I get back.)

**Comment by tomaae** [comment]
Any update on this?

**Comment by emresumengen** [comment]
Sorry @tomaae for the lack of response from my end... Having problems with my RPi3, I’m now waiting for a suitable time to move everything over to a NUC + Dockerized HA.
Unfortunately, remote-working is taking more time than I anticipated nowadays.

**Comment by tomaae** [comment]
No problem at all, take all the time you need.
And yeah, I left RPI for HA behind after 2 weeks. It was painfully slow to work with and using sdcard for writes like that is always unreliable.
I got cheap mini pc, similar to NUC and use NUC version of HA, so its same as version for RPI. Now I use that RPI for HA kiosk.
