### ISSUE TITLE
[Feature] Manage and monitor PoE ports

### ISSUE THREAD

**Issue by benedikt-bartscher** [tomaae/homeassistant-mikrotik_router#71]
I would be awesome if we could switch PoE Ports on/off or monitor the power usage per port

**Comment by tomaae** [comment]
that would be really useful feature for anyone who uses poe, I agree.
but it is a difficult one, since I dont think I have any mikrotik device with poe. I will have to look up all models I own and see

**Comment by benedikt-bartscher** [comment]
I think the HEX PoE (RB960PGS) is the smallest and cheapest 803.3at/af switch from mikrotik. I have access to some of those and if it works i will buy a bigger one too. If there is something i could test for you, i am pleased to help!

**Comment by tomaae** [comment]
Looks like my main router, rb4011igs+ has one poe, at least I'm assuming so based on this:
![image](https://user-images.githubusercontent.com/23486452/99464976-a438e980-2939-11eb-96a6-f19a71da835b.png)
cAP ac which I have in my dev environment for this integration should accept it. I will have to confirm the compatibility before trying, dont want to burn it out.
May be a bit problematic, since I have my dev env isolated for obvious reasons, but I will think of something once I have time to work on it, or just disable wifi for the time being.

**Comment by tomaae** [comment]
Port switch now controls PoE as well if port has such capability.
I did not found any way to get PoE power usage. It is in documentation, but it does not show up in routeros output.
