### ISSUE TITLE
[Feature] Add firewall mangle control

### ISSUE THREAD

**Issue by mehale** [tomaae/homeassistant-mikrotik_router#75]
## Is your feature request related to a problem? Please describe.

Some people use mangle firewall rules to control wether packets or connections should be caught by queues, routes, etc. For example I tag packets to set them to be routed thru a VPN connection.

## Describe the solution you'd like

Just add the on/off control possibility, as with other stuff as NAT and queues.

## Additional context

Thanks for the great integration!

**Comment by tomaae** [comment]
Controlling connection markers? What would be an use case for such feature?

**Comment by mehale** [comment]
Connection, packet markers and routing markers add a great flexibility for the system.
They can be used to control traffic going thru: routes, firewall filter rules, NAT, queues.

My personal use case right now is: 

When I need certain hosts traffic go thru a VPN, I set a routing mark and then there is a routing rule that will route that thru the VPN. It would be awesome to be able to control traffic to be sent thru the VPN from home assistant.

**Comment by tomaae** [comment]
Sure thing. I just needed to understand the use case, so its implemented properly.

**Comment by tomaae** [comment]
![image](https://user-images.githubusercontent.com/23486452/102650422-34519500-416b-11eb-9ba9-8c898c70fadd.png)
Mangles have same issue as NAT. There is no persistent unique ID, so have to decide on something and ignore everything that is outside of that specification.
So far I went for protocol and destination port, since thats unique for how I use mangles. How do you see it?

**Comment by mehale** [comment]
Cant we address the mangle rule by its name, provided it has an unique name? 

If thats not possible, or no name has been set, maybe: chain, protocol, dst port, src port, src address, dst address, src and dst address list. I am not sure what "fields" we could use, but those are the ones I use most.

**Comment by tomaae** [comment]
mangle rules dont have names at all.

that is way too many fields to use for name itself. for unique id we can use whatever we want, but name itself must be clearly descriptive.

**Comment by mehale** [comment]
Sorry, I actually had the comment field in mind and confused that with "name". Would it be possible to filter by comment?

For naming, maybe get the first 3 or 4 not empty fields.

```
/ip firewall mangle print where comment~"ABC"     
Flags: X - disabled, I - invalid, D - dynamic 
 0 X  ;;; ABC
      chain=prerouting action=mark-routing new-routing-mark=VIA_VPN passthrough=yes src-address=192.168.12.0/24 dst-address=!192.168.0.0/16 log=no log-prefix="" 

```

**Comment by tomaae** [comment]
Yes, it would be possible to limit them by comment. but then comment would have to be unique and cannot be changed.
I have to query specific field, thats what is causing issues with NAT and Mangle. Since most fields are optional, we will have to make a decision on what to limit this to.

Maybe:
chain;action;protocol;src-add:src-ports->dst-add:dst-ports
Cant use mark, as that one has different field name for each type.
would this meet your requirements? in case there would be duplicates, they would get hidden and warning would be shown in the log.

**Comment by mehale** [comment]
It seems ok to me.

**Comment by tomaae** [comment]
All done. Since such name looks wonky, it will display comment as name instead if it is available.
Give it a try.

**Comment by mehale** [comment]
How should I test it? 
I switched HACS version from 1.5.10 to master (shows now 873a939), restarted home assistant, but I cannot see the  mangle rules.
I am sure I am missing something :)

**Comment by tomaae** [comment]
Enable sensors you need in options. You wont see text there, so use this as guide:
![image](https://user-images.githubusercontent.com/23486452/103156188-85ced500-47a6-11eb-95c7-ef301dc7dd79.png)

**Comment by mehale** [comment]
When I go to integration/mikortik_router/options, all I get is this:

![image](https://user-images.githubusercontent.com/2956657/103158657-e9adc980-47b7-11eb-9176-a1414fcb59e5.png)

I even deleted the HACS integration and added it back again... tried with master and 1.5.10

**Comment by tomaae** [comment]
yes, there are no translations in master. just press submit and you will get 2nd page.

**Comment by mehale** [comment]
I see now, it works like a charm!
Thank you!

**Comment by tomaae** [comment]
perfect 👍
